# Generated by Django 6.0.6 on 2026-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='closes',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='opens',
            field=models.CharField(),
        ),
    ]
