# Generated by Django 6.0.6 on 2026-06-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_alter_businessmodel_owner'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mmessage', models.TextField()),
                ('announcement_type', models.CharField(choices=[('NEW_BUSINESS', 'New Business'), ('NEW_PRODUCT', 'New Product')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='business.businessmodel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
