# Generated by Django 6.0.6 on 2026-06-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementmodel',
            old_name='mmessage',
            new_name='message',
        ),
    ]
